CREATE TABLE public.events
(
    id serial,
	ACQ_CHARTAGENT varchar(10) NULL, 
	ACQ_CNTYNAME varchar(50) NULL, 	
	ACQ_CNTYNUM integer NULL, 	
	ACQ_FDICREGION integer NULL, 	
	ACQ_FDICREGION_DESC varchar(75) NULL, 	
	ACQ_INSTNAME varchar(200) NULL,	
	ACQ_ORGTYPE_NUM integer NULL, 	
	ACQ_ORG_EFF_DTE date NULL, 	
	ACQ_PADDR varchar(200) NULL, 	
	ACQ_PCITY varchar(50) NULL, 	
	ACQ_PSTALP varchar(10) NULL, 	
	ACQ_PSTNUM integer NULL, 	
	ACQ_PZIP5 varchar(10) NULL, 	
	ACQ_PZIPREST varchar(10) NULL, 	
	ACQ_REGAGENT varchar(10) NULL, 	
	CHANGECODE_DESC_LONG varchar(255) NULL, 	
	EFFYEAR varchar(10) NULL, 	
	OUT_CHARTAGENT varchar(10) NULL, 
	OUT_CNTYNAME varchar(50) NULL, 	
	OUT_CNTYNUM integer NULL, 	
	OUT_FDICREGION integer NULL, 	
	OUT_FDICREGION_DESC varchar(75) NULL, 	
	OUT_INSTNAME varchar(200) NULL,	
	OUT_ORGTYPE_NUM integer NULL, 	
	OUT_PADDR varchar(200) NULL, 	
	OUT_PCITY varchar(50) NULL, 	
	OUT_PSTALP varchar(10) NULL, 	
	OUT_PSTNUM integer NULL, 	
	OUT_PZIP5 varchar(10) NULL, 	
	OUT_PZIPREST varchar(10) NULL, 	
	OUT_REGAGENT varchar(10) NULL,
	PROCDATE date NULL, 	
	PROCYEAR varchar(10) NULL, 	
	PSTALP varchar(10) NULL, 	
	REGAGENT varchar(10) NULL, 	
	SUR_CHARTAGENT varchar(10) NULL, 	
	SUR_CNTYNUM integer NULL, 	
	SUR_FDICREGION integer NULL, 	
	SUR_FDICREGION_DESC varchar(75) NULL, 	
	SUR_INSTNAME varchar(200) NULL, 
	SUR_MADDR varchar(200) NULL, 	
	SUR_MCITY varchar(50) NULL, 	
	SUR_MSTALP varchar(10) NULL, 	
	SUR_MSTATE varchar(40) NULL, 	
	SUR_MZIP5 varchar(10) NULL, 	
	SUR_ORGTYPE_NUM integer NULL, 	
	SUR_PADDR varchar(200) NULL, 	
	SUR_PCITY varchar(50) NULL, 	
	SUR_PSTALP varchar(10) NULL, 	
	SUR_PSTNUM integer NULL, 	
	SUR_PZIP5 varchar(10) NULL, 	
	SUR_PZIPREST varchar(10) NULL, 	
	SUR_REGAGENT varchar(10) NULL, 
    CONSTRAINT events_pkey1 PRIMARY KEY (id)
)

TABLESPACE pg_default;


 
	